### ISSUE TITLE
Use gobgp?

### ISSUE THREAD

**Issue by bzed** [davidcoles/cue#1]
Hi,

any reason why you've implemented your own bgp code instead of using gobgp?

Thanks,
Bernd

**Comment by davidcoles** [comment]
Probably not a good one. I did look at gpbgp but figured that understanding how to use it would take at least as long as writing a basic BGP implementtion from scratch (and learning something in the process). Becase it only needs to advertise /32 prefixes and doesn't need to know anything about the routing tables that peers have it is a mostly trivial implementation.

Of course, with the possibility of IPv6 coming up and (I guess) needing multiprotocol BGP then maybe I need to revisit this - have you managed to ingegrate gpbgp into your own projects?

Cheers,
David

**Comment by bzed** [comment]
We only know gobgp from other open source projects and as stand-alone bgp daemon. Unfortunately we don't have much free go developer time, so we are happy to fix bugs and maybe add small features, but when considering a new software rewriting parts of it might be out of scope. But nothing decided yet.

We've reviewed your code and basically our networking team denied using some unknown and maybe incomplete bgp implementation in our network - which is something I can fully understand as our bgp setup is far far far away from simple. Gobgp is battle proven in lots of big projects and tested in our setup, too - so thats the reason behind it.

Looking at https://github.com/osrg/gobgp/blob/master/docs/sources/lib.md it seems to be rather easy to re-implement your bgp code using gobgp.

**Comment by bzed** [comment]
Running gobgp as external daemon and talking to its api is also a good option as it is much more flexible - you can configure gobgp as you need it and just tell it via gRPC api to announce/delete the routes. Needs proper handling of the connection to the bgp daemon of course, but its a good option for more flexibility without having to include the whole bgp configuration part into your own software (cilium does that for example, and its rather annoying to configure).

**Comment by davidcoles** [comment]
My thinking was that when the load balancer exits (or possibly panics) you REALLY want the routes to be withdrawn because otherwise you will end up blackholing traffic, so embedding the connection to the peer into that process automatically terminates the session. I kind of wanted a single, simple piece of code that we could configure in one place rather than having to plumb a number of systems together.

If there is a way ensure the same thing with a gRPC connection then that would be just as good - but I will have to take the time learn that API.

The interface from vc5/cue to BGP is very simple ("here's a list of IPs, advertise them!"), so replacing it with a different implementation should be quite trivial.

I had originally written everything in on project, but I have since split out most of the functionality into seperate project (cue for doing the control plane and xvs for talking to the XDP code in the kernel), so vc5 is now just the thing which ties them together and kind of serves as an example of how one could build a more tailored solution - for example, my stayinalived repo is vc5 but with the XDP bit ripped out an replaced with IPVS/LVS.

Maybe a similar remix that uses gobgp is a possibility?

**Comment by davidcoles** [comment]
Apologies - I didn't see your first reply initially. I'll have a look at that embedded GoBGP example.

**Comment by davidcoles** [comment]
I've managed to get iBGP and eBGP sessions up and advertising IPs, so it should be fairly easy to write a module which can be swapped in for the .../cue/bgp module

This will certainly make supporting IPv6 in the near(ish) future a lot easier ;-)

(it sure pulls in a lot of dependencies though!)

**Comment by davidcoles** [comment]
Hi Bernd.

I've not really had chance to look into this, but it did strike me that it would be possible to achieve what you are requesting by simply connecting to GoBGP (or BIRD, etc) from within the network namespace that I use for sourcing probe requests to the correct VIP/MAC address on the backend servers.

I've just had a quick hack at this and it seems to work without any issue.

I'm just running BIRD on the load balancer server with peering to the router to which I want to advertise VIPs, and another peer with the address of the veth interface in the network namespace.

So my BGP library is then only used to talk to BIRD on the local interface, and then BIRD re-advertises the VIPS out to the network, giving you the option to make any adjustments that you want (add communities, local pref, MED, etc).

Would this work for your purposes?

**Comment by bzed** [comment]
Hi David,

that would be perfectly fine! Bird is our favourite bgp server, so this would make our life easy.

Thanks for considering,
Bernd

**Comment by davidcoles** [comment]
No worries :-)

Actually, even easier, it turns out that it's possible to connect to BIRD over the loopback interface!

If you pull and build the latest version of vc5 then you should be able to start using it right away.

Just use the `-A <as_number>` flag when running the binary and it will try to connect to a peer on 127.0.0.1

The BIRD config that I got this running with is detailed at:

https://github.com/davidcoles/vc5/blob/master/doc/bgp.md

Cheers,
David

**Comment by davidcoles** [comment]
I'll close this now as it's something that can be done in vc5, rather than a change needed here.

Thanks for the suggestion.
